name: dbt CI

on:
  pull_request:
    branches: [ "dev", "master" ]
  push:
    branches: [ "feature/python-models" ]  

jobs:
  dbt-ci:
    runs-on: ubuntu-latest
    environment: DBT_BTC

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core==1.9.4 dbt-snowflake==1.11.6

      - name: Write profiles.yml + private key
        shell: bash
        run: |
          mkdir -p /home/runner/.dbt
          echo "${{ secrets.DBT_PROFILES_YML }}" > /home/runner/.dbt/profiles.yml
          echo "${{ secrets.DBT_PRIVATE_KEY }}" > /home/runner/.dbt/rsa_key
          chmod 600 /home/runner/.dbt/rsa_key

      - name: Install dbt deps
        run: dbt deps

      - name: Debug connection
        run: dbt debug --target dev

      - name: Run models + tests
        run: dbt build --target dev

